config/routes.rb
Rails.application.routes.draw do
  
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: :show
    resources :categories,          only: :show
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.includes(:root)
    @products = Spree::Product.in_taxon(@taxon).includes(master: [:images, :default_price])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.find(params[:id])
    @product_properties = @product.product_properties.includes(:property)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <!-- SITE TITTLE -->
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <!-- GOOGLE FONT -->
    <!-- CUSTOM CSS -->
    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->  
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <%= render 'shared/shim' %>
  </head>

  <body>
    <div class="main-wrapper">
      <%= render 'shared/header' %>
      <%= yield %>
      <%= render 'shared/footer' %>
      <%= render 'shared/copyright' %>
      <%= render 'shared/login' %>
      <%= render 'shared/signup' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_filter_area.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
    </div>
  </div>
</div>

app/views/potepan/categories/_page_title.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="index.html">Home</a>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_partners_logo.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(product.display_image.attachment.url) %> 
      <div class="productMasking">
        <ul class="list-inline btn-group" role="group">
          <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
          <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
          <li><a class="btn btn-default" data-toggle="modal" href="#"><i class="fa fa-eye"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="productCaption clearfix">
      <%= link_to potepan_product_path(product.id) do %>
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3> 
      <% end %>     
    </div>
  </div>
</div>

app/views/potepan/categories/_sidebar.html.erb
<div class="panel panel-default priceRange">
  <div class="panel-heading">値段から探す</div>
  <div class="panel-body clearfix">
    <div class="price-slider-inner">
      <span class="amount-wrapper">
        <input type="text" id="price-amount-1" readonly>
        <strong>-</strong>
        <input type="text" id="price-amount-2" readonly>
      </span>
      <div id="price-range"></div>
    </div>
    <input class="btn btn-default" type="submit" value="絞り込む">
    <!-- <span class="priceLabel">Price: <strong>12 円- 30<円/strong></span> -->
  </div>
</div>
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <li><a href="#">ブラック<span>(15)</span></a></li>
      <li><a href="#">ホワイト<span>(10)</span></a></li>
      <li><a href="#">レッド<span>(7)</span></a></li>
      <li><a href="#">ブルー<span>(12)</span></a></li>
      <li><a href="#">オレンジ<span>(12)</span></a></li>
    </ul>
  </div>
</div>
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <li><a href="#">S<span>(15)</span></a></li>
      <li><a href="#">M<span>(10)</span></a></li>
      <li><a href="#">L<span>(7)</span></a></li>
      <li><a href="#">XL<span>(12)</span></a></li>
    </ul>
  </div>
</div>

app/views/potepan/categories/_taxonomies.html.erb
<div class="panel-heading">商品カテゴリー</div>
<div class="panel-body">
  <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
    <ul class="nav navbar-nav side-nav">
      <% taxonomies.each do |taxonomy| %> 
        <li>
          <a href="javascript:;" data-toggle="collapse" data-target="#taxonomy_<%= taxonomy.id %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
          <ul id="taxonomy_<%= taxonomy.id %>" class="collapse collapseItem">             
            <% taxonomy.root.leaves.each do |taxon| %>
              <li>
                <%= link_to potepan_category_path(taxon.id) do %>
                  <i class="fa fa-caret-right" aria-hidden="true"></i>
                  <%= taxon.name %><span>(<%= taxon.products.count %>)</span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>

<%= render partial: 'page_title', locals: { taxon: @taxon } %>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <div class="panel panel-default">
          <%= render partial: 'taxonomies', locals: { taxonomies: @taxonomies } %>
        </div>
        <%= render partial: 'sidebar' %>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <%= render partial: 'filter_area' %>
        <div class="row">
          <%= render partial: 'product', collection: @products, as: :product %>            
        </div>
      </div>
    </div>
  </div>
</section>
<%= render partial: 'partners_logo' %>

app/views/potepan/products/_image.html.erb
<div class="media-left productSlider">
  <div id="carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <%# 商品画像 %>
      <% product.images.each_with_index do |image, i| %>
        <div class="item <%= 'active' if i.zero? %>" data-thumb="<%= i %>">
          <%= image_tag(image.attachment(:large)) %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="clearfix">
    <div id="thumbcarousel" class="carousel slide" data-interval="false">
      <div class="carousel-inner">
        <%# 商品画像一覧 %>
        <% product.images.each_with_index do |image, i| %>
          <div data-target="#carousel" data-slide-to="<%= i %>" class="thumb">
            <%= image_tag(image.attachment(:small)) %>
          </div>        
        <% end %>
      </div>
        <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
  </div>
</div>

app/views/potepan/products/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2>
            <%= product.name %>
          </h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="index.html">Home</a>
          </li>
          <li class="active"><%= product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_product_details.html.erb
<div class="media-body">
  <ul class="list-inline">
    <li><a href="product_grid_left_sidebar.html"><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</a></li>
    <!-- <li><a href="#"><i class="fa fa-plus" aria-hidden="true"></i>Share This</a></li> -->
  </ul>
  <%# クリックした商品の名前、値段、写真が表示されるように設定する %>
  <h2><%= product.name %></h2>
  <h3><%= product.display_price %></h3>
  <p><%= product.description %></p>
  <span class="quick-drop">
    <select name="guiest_id3" id="guiest_id3" class="select-drop">
      <option value="0">S</option>
      <option value="1">M</option>
      <option value="2">L</option>
      <option value="3">XL</option>
    </select>
  </span>
  <span class="quick-drop resizeWidth">
    <select name="guiest_id4" id="guiest_id4" class="select-drop">
      <!--   <option value="0">Qty</option> -->
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
    </select>
  </span>
  <div class="btn-area">
    <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
  </div>

  <div class="tabArea">
    <%# タブの中身 %>
    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#details">details</a></li>
      <li><a data-toggle="tab" href="#about-art">about art</a></li>
      <li><a data-toggle="tab" href="#sizing">sizing</a></li>
      <li><a data-toggle="tab" href="#shipping">shipping</a></li>
    </ul>

    <div class="tab-content">
      <div id="details" class="tab-pane fade in active">
        <%# プロパティの実装 %>
        <% if product_properties.present? %>
          <% product_properties.each do |product_property| %>
            <ul class="properties area">
              <li>
                <strong><%= product_property.property.presentation %></strong>
                <%= product_property.value %>
              </li>
            </ul>
          <% end %>
        <% end %>
      </div>

      <div id="about-art" class="tab-pane fade">
        <p>Nulla facilisi. Mauris efficitur, massa et iaculis accumsan, mauris velit ultrices purus, quis
          condimentum nibh dolor ut tortor. Donec egestas tortor quis mattis gravida. Ut efficitur elit
          vitae dignissim volutpat. </p>
      </div>
      <div id="sizing" class="tab-pane fade">
        <p>Praesent dui felis, gravida a auctor at, facilisis commodo ipsum. Cras eu faucibus justo. Nullam
          varius cursus nisi, sed elementum sem sagittis at. Nulla tellus massa, vestibulum a commodo
          facilisis, pulvinar convallis nunc.</p>
      </div>
      <div id="shipping" class="tab-pane fade">
        <p>Mauris lobortis augue ex, ut faucibus nisi mollis ac. Sed volutpat scelerisque ex ut
          ullamcorper. Cras at velit quis sapien dapibus laoreet a id odio. Sed sit amet accumsan ante, eu
          congue metus. Aenean eros tortor, cursus quis feugiat sed, vestibulum vel purus.</p>
      </div>
    </div>
  </div>
</div>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div> 　
  </div>

  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag("img/products/products-01.jpg", :alt => "products-img") %>
        <div class="productMasking">
          <ul class="list-inline btn-group" role="group">
            <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
            <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
            <li><a class="btn btn-default" data-toggle="modal" href=".quick-view"><i class="fa fa-eye"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="productCaption clearfix">
        <h5>Nike Sportswear</h5>
        <h3>199円</h3>
      </div>
    </div> 　
  </div>

  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag("img/products/products-02.jpg", :alt => "products-img") %>
        <div class="productMasking">
          <ul class="list-inline btn-group" role="group">
            <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
            <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
            <li><a class="btn btn-default" data-toggle="modal" href=".quick-view"><i class="fa fa-eye"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="productCaption clearfix">
        <h5>Dip Dyed Sweater</h5>
        <h3>249円</h3>
      </div>
    </div> 　
  </div>

  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag("img/products/products-03.jpg", :alt => "products-img") %>
        <div class="productMasking">
          <ul class="list-inline btn-group" role="group">
            <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
            <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
            <li><a class="btn btn-default" data-toggle="modal" href=".quick-view"><i class="fa fa-eye"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="productCaption clearfix">
        <h5>Scarf Ring Corner</h5>
        <h3>179円</h3>
      </div>
    </div> 　
  </div>

  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag("img/products/products-04.jpg", :alt => "products-img") %>
        <div class="productMasking">
          <ul class="list-inline btn-group" role="group">
            <li><a data-toggle="modal" href=".login-modal" class="btn btn-default"><i class="fa fa-heart"></i></a></li>
            <li><a href="cart_page.html" class="btn btn-default"><i class="fa fa-shopping-cart"></i></a></li>
            <li><a class="btn btn-default" data-toggle="modal" href=".quick-view"><i class="fa fa-eye"></i></a></li>
          </ul>
        </div>
      </div>
      <div class="productCaption clearfix">
        <h5>Sun Buddies</h5>
        <h3>149円</h3>
      </div>
    </div> 　
  </div>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title,@product.name) %>

<%= render partial: 'light_section', locals: { product: @product } %>

<!-- MAIN CONTENT SECTION -->

<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <%= render partial: 'image', locals: { product: @product } %>
          <%= render partial: 'product_details', locals: { product: @product, product_properties: @product_properties } %>
        </div>
      </div>
    </div>
    <%= render partial: 'related_products' %>
  </div>
</section>

app/views/potepan/sample/cart_page.html.erb
<% provide(:title,"Cart Page") %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeaderImage">
  <div class="container">
    <div class="tableBlock">
      <div class="row tableInner">
        <div class="col-xs-12">
          <div class="page-title">
            <h2>cart</h2>
            <ol class="breadcrumb">
              <li>
                <a href="index.html">Home</a>
              </li>
              <li class="active">cart</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix cartListWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="cartListInner">
          <form action="#">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th></th>
                    <th>商品名</th>
                    <th>価格</th>
                    <th>数</th>
                    <th>小計</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="updateArea">
              <!--  <div class="input-group">
                    <input type="text" class="form-control" placeholder="I have a discount coupon" aria-describedby="basic-addon2">
                    <a href="#" class="btn input-group-addon" id="basic-addon2">apply coupon</a>
                  </div> -->
              <a href="#" class="btn">アップデート</a>
            </div>
            <div class="totalAmountArea">
              <div class="col-sm-4 col-sm-offset-8 col-xs-12">
                <ul class="list-unstyled">
                  <li>小計 <span>792円</span></li>
                  <li>消費税 <span>18円</span></li>
                  <li>総計 <span class="grandTotal">810円</span></li>
                </ul>
              </div>
            </div>
            <div class="checkBtnArea">
              <a href="checkout_step_1.html" class="btn btn-primary btn-block">購入する<i class="fa fa-arrow-circle-right"aria-hidden="true"></i></a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>  
</section>

app/views/potepan/sample/checkout_complete.html.erb
<% provide(:title,"Order Completed") %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2>thanks message</h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="index.html">Home</a>
          </li>
          <li class="active">thanks message</li>
        </ol>
      </div>
    </div>
  </div>
</section>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix setp5">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="thanksContent">
          <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
          <h3>Shipping Details</h3>
          <div class="thanksInner">
            <div class="row">
              <div class="col-sm-6 col-xs-12 tableBlcok">
                <address>
                  <span>Shipping address:</span> <a href="mailto:adamsmith@bigbag.com">adamsmith@bigbag.com</a> <br>
                  <span>Email:</span> <a href="mailto:adamsmith@bigbag.com">adamsmith@bigbag.com</a> <br>
                  <span>Phone:</span> +884 5452 6432
                </address>
              </div>
              <div class="col-sm-6 col-xs-12">
                <div class="well">
                  <h2><small>Order ID</small>9547</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>  
</section>

app/views/shared/_header.html.erb
<div class="header clearfix">
  <%= render 'shared/topbar'%>
  <%= render 'shared/navbar'%>
</div>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->